/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tarea09;

/**
 *
 * @author Frida Paolette Ramirez-Lara
 */
public class ColorSel extends javax.swing.JPanel {

    /**
     * Creates new form ColorSel
     */
    public ColorSel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        comboColor = new javax.swing.JComboBox<>();
        panelCentro = new javax.swing.JPanel();
        backgroundCB = new javax.swing.JCheckBox();
        foregroundCB = new javax.swing.JCheckBox();
        panelSur = new javax.swing.JPanel();
        botonOK = new javax.swing.JButton();
        botonCANCEL = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.GridLayout());

        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red" }));
        panelNorte.add(comboColor);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        backgroundCB.setText("Background");
        backgroundCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(backgroundCB);

        foregroundCB.setText("Foreground");
        foregroundCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foregroundCB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(foregroundCB);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        botonOK.setText("Ok");
        panelSur.add(botonOK);

        botonCANCEL.setText("Cancel");
        panelSur.add(botonCANCEL);

        add(panelSur, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backgroundCB;
    private javax.swing.JButton botonCANCEL;
    private javax.swing.JButton botonOK;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JCheckBox foregroundCB;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    // End of variables declaration//GEN-END:variables
}
